### PR TITLE
Added functionality for specifying branches

### PR DESCRIPTION
**Pull request by magicaltrevor**
Made these changes for internal project. I'm not really familiar with cucumber testing so I didn't update the tests. Just sending these to you if you'd like to use them. Thanks for this AWESOME tool!

### CODE REVIEW

**Comment by foolo** [comment]
bump!
we are using this fork instead of the "official" repo, to get this feature

**Comment by Club15CC** [comment]
Nice feature!

**Comment by barraq** [comment]
@patmaddox why is this PR still not reviewed? Sounds like a really nice extension... actually I was thinking about implementing it myself. Having the ability to specify tags/branches is a must have. Don't you think?

**Comment by Air-Craft** [comment]
I think this project is nearly dead. It's a shame because it's by far the best solution I've used, at least in iOS development. I've started abandoning it though due to lack of a reliable future :(

**Comment by jwhitley** [comment]
This repo has been unmaintained for years; it happens.  That said, the codebase is small and fairly easily understood.  If you like the functionality in this PR, then make a fork and merge this PR into it.

Alternatively, I would recommend looking at the [`mr`](http://myrepos.branchable.com/) tool, and possibly [`vcsh`](https://github.com/RichiH/vcsh) depending on your use cases.  Both of these are stable, maintained tools.  There's not a ton of feature activity, as they're pretty mature for what they do.  New PRs do occasionally spring up and get merged when users bring them up.

`mr` (aka "myrepos") is a workflow tool designed to manage tasks across a set of repositories (not necessarily even git repos) in unison.  `vcsh` is designed to manage a set of repos structured to overlap the same root directory without using symlinks.  `vcsh` is one of the more popular tools for those of us who want to version control their home directories, but find it useful to split those concerns across several repositories.  Sometimes this is topical (e.g. shell rc files vs. editor config, etc.), but can also be used to separate other specific needs (e.g. personal dev setup vs. work setup).  `vcsh` and `mr` can work nicely in tandem to handle some use-cases, but many people will find that just one or the other works fine depending on their specific needs.

**Comment by patmaddox** [comment]
I don't actively use this tool anymore. I'd be merging pull requests without even trying them, which is no bueno.

I'll update the README to indicate that it's no longer maintained, and to include the alternatives that @jwhitley suggested.

**Pull request closed without merging**
